### ISSUE TITLE
Please reformat the repository

### ISSUE THREAD

**Issue by SHIccc** [QuantLet/TENET#1]
I gave you an example of "**TENET_totalconnectedness**", please change your codes and Metainfo file accordingly. 

Please pay attention to:
1. **Rename** your repository, for instance, "TENET_group_network" is better than "plot_group_network"
2. **Update your KW**. The keyword list is available on http://quantlet.com/index.php?p=searchResults&w=allkeywords
3. **Example** in Metainfo.txt: contains a list of generated plots and description, which is not written in other meta-info fields, for example, description of the output plot.

**Comment by yulining** [comment]
Thanks very much! I have changed all the files according to your comments.
